[project]
name = "flyin"
version = "1.3"
description = "Drone Pathfinding and Path Assignment Optimizer"
readme = "README.md"
authors = [
    { name = "dansimoe" }
]
requires-python = ">=3.10"
dependencies = [
	"pydantic",
	"pygame",
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
]

[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = ["pygame.*", "pygame"]
ignore_missing_imports = true
